IMP-171: Add route blacklist check
valitydev/hellgate pull request #119
Opened 2024-03-06 07:58 UTC by WWWcool

2024-03-11 12:05 UTC, nanodirijabl requested changes

2024-03-11 12:05 UTC, nanodirijabl commented on apps/routing/src/hg_routing.erl
> +                hg_routing_ctx:reject(in_blacklist, R1, C);
В `hg_invoice_payment` должна быть функция для логирования отвергнутых маршрутов. Надо туда добавить [клозу для `in_blacklist`](https://github.com/valitydev/hellgate/blob/d354b3e175f203b92f6c0fc28c159a2246b796ec/apps/hellgate/src/hg_invoice_payment.erl#L807-L824).
Логику роутинга вынесли оттуда, но хвосты ещё остались.

2024-03-11 12:05 UTC, nanodirijabl commented on apps/hellgate/test/hg_invoice_lite_tests_SUITE.erl
> -            attempt_limit = {value, #domain_AttemptLimit{attempts = 2}}
Смущает это значение. Наверное я его добавлял, но может это было и опечаткой.

2024-03-11 13:40 UTC, WWWcool commented on apps/hellgate/test/hg_invoice_lite_tests_SUITE.erl
> -            attempt_limit = {value, #domain_AttemptLimit{attempts = 2}}
это лайт сьют - возможно копипаста конфига, у меня из за этого на каскад уходили платежи когда я второй урот добавил, до этого тут только один кандидат был

2024-03-12 16:19 UTC, strug commented on apps/hellgate/test/hg_dummy_inspector.erl
> +    'isExistInBlackList',
поменять можно, но с вас протокол и все дела тогда

2024-03-12 16:33 UTC, WWWcool commented on apps/hellgate/test/hg_dummy_inspector.erl
> +    'isExistInBlackList',
ок

2024-03-13 09:14 UTC, WWWcool commented on apps/hellgate/test/hg_dummy_inspector.erl
> +    'isExistInBlackList',
https://github.com/valitydev/damsel/pull/121

2024-03-15 10:38 UTC, nanodirijabl commented on apps/routing/src/hg_routing.erl
> +-export([check_routes/2]).
Не понял зачем она экспортируется и оборачивает оценку роутов инспектором.

2024-03-15 10:38 UTC, nanodirijabl commented on apps/hellgate/test/hg_invoice_lite_tests_SUITE.erl
> +    erlang:display([Explanation]).
Забытое? Может там ассерт должен был быть?

2024-03-18 08:56 UTC, nanodirijabl approved these changes

2024-03-18 09:07 UTC, merged